services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=DBuser
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=dp_pessoas
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"